version: '3.8'

services:
  db:
    build: db/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    build: backend/
    environment:
      - TOKEN_EXPIRED=3600000
    ports:
      - "9090:9090"
    depends_on:
      - db

  frontend:
    build: frontend/
    ports:
      - "8080:8080"
    depends_on:
      - backend

