server:
  port: 9090
spring:
#  profiles: dev
  application:
    name: notebookservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notebooks
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
