server:
  port: 9090

spring:
  application:
    name: notebookservice
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/notebook
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog.xml

jwt:
  token:
    secret: notebookapp
    expired: ${TOKEN_EXPIRED:3600000}
