server:
  port: 9090
spring:
#  profiles: dev
  application:
    name: notebookservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notebooks
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog.xml

jwt:
  token:
    secret: notebookapp
    expired: 3600000